/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_appsync_graphqlEndpoint": "https://zkfusjkg55gf3emmeagoth6m6a.appsync-api.us-east-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-2",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-lvc3sn4usjbxxdnjxmeoprpb7y",
    "Auth": {
        "region": "us-east-2",
        "userPoolId": "us-east-2_qFqFIbjDz",
        "userPoolWebClientId": "6p72lr2g6tg5pv16cci9j7m5ov",
        "oauth": {
            "domain": "us-east-2qfqfibjdz.auth.us-east-2.amazoncognito.com",
            "scope": [
                "openid",
                "email",
                "phone",
                "profile"
            ],
            "redirectSignIn": "http://localhost:3000/",
            "redirectSignOut": "http://localhost:3000/",
            "responseType": "code"
        }
    }
};


export default awsmobile;
